/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import asignaciontecnicas.Persona;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Santamaria
 */
public class listarusu extends javax.swing.JFrame {

    /**
     * Creates new form listarusu
     */
    //public static List<Contacto> listado = new ArrayList<>();
    public static List<Persona> listar = new ArrayList<>();
    static private DefaultListModel miLista;

    public listarusu() {
        initComponents();
        setLocationRelativeTo(null);
        setListadoGrafico();
    }

    public void printListado() {
        for (Persona persona : listar) {
            System.out.println(persona);
        }
    }

    static private void setListadoGrafico() {
        if (jlVer==null) {
            return;
        }

        miLista = new DefaultListModel();
        for (Persona persona : listar) {
            miLista.addElement(persona.getNombre());
        }

        jlVer.setModel(miLista);
    }

    static public void addPersona(Persona c) {
        listar.add(c);
        setListadoGrafico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbListus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlVer = new javax.swing.JList();
        btMostrar = new javax.swing.JButton();
        lbLista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(258, 440));
        setMinimumSize(new java.awt.Dimension(258, 440));
        setPreferredSize(new java.awt.Dimension(258, 440));
        setResizable(false);
        getContentPane().setLayout(null);

        lbListus.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        lbListus.setForeground(new java.awt.Color(102, 153, 255));
        lbListus.setText("LISTA DE USUARIOS");
        getContentPane().add(lbListus);
        lbListus.setBounds(10, 10, 240, 20);

        jScrollPane1.setViewportView(jlVer);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 70, 190, 290);

        btMostrar.setBackground(new java.awt.Color(0, 153, 255));
        btMostrar.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        btMostrar.setForeground(new java.awt.Color(0, 0, 0));
        btMostrar.setText("MOSTRAR");
        btMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMostrarMouseClicked(evt);
            }
        });
        getContentPane().add(btMostrar);
        btMostrar.setBounds(50, 380, 150, 40);

        lbLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/arbolmadre.jpg"))); // NOI18N
        getContentPane().add(lbLista);
        lbLista.setBounds(0, 0, 260, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMostrarMouseClicked
        // TODO add your handling code here:
        
         if (jlVer.getSelectedIndex() != -1) {

            new registrarp(
                    listar.get(jlVer.getSelectedIndex())
            ).setVisible(true);
        }
        
        
    }//GEN-LAST:event_btMostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listarusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listarusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listarusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listarusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listarusu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JList jlVer;
    private javax.swing.JLabel lbLista;
    private javax.swing.JLabel lbListus;
    // End of variables declaration//GEN-END:variables
}
