/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import asignaciontecnicas.Persona;

/**
 *
 * @author Santamaria
 */
public class registrarp extends javax.swing.JFrame {

    /**
     * Creates new form registrarp
     */
    public registrarp() {
        initComponents();
        setLocationRelativeTo(null);
    }

    registrarp(Persona c) {
    
        tfNombre.setText(c.getNombre());
        tfCedula.setText(c.getCedula());
        spEdad.setValue(c.getEdad());
        
//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRegistrar = new javax.swing.JButton();
        btLista = new javax.swing.JButton();
        LbTitulo = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbCedula = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spEdad = new javax.swing.JSpinner();
        tfNombre = new javax.swing.JTextField();
        tfCedula = new javax.swing.JTextField();
        LbPanel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(611, 440));
        setName("jfPrincipal"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        btRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        btRegistrar.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        btRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btRegistrar.setText("REGISTRAR");
        btRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegistrarMouseClicked(evt);
            }
        });
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistrar);
        btRegistrar.setBounds(90, 340, 132, 46);

        btLista.setBackground(new java.awt.Color(102, 153, 255));
        btLista.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        btLista.setForeground(new java.awt.Color(0, 0, 0));
        btLista.setText("LISTADO");
        btLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btListaMouseClicked(evt);
            }
        });
        getContentPane().add(btLista);
        btLista.setBounds(370, 340, 143, 46);

        LbTitulo.setFont(new java.awt.Font("sansserif", 3, 48)); // NOI18N
        LbTitulo.setForeground(new java.awt.Color(102, 102, 255));
        LbTitulo.setText("REGISTRAR USUARIO");
        getContentPane().add(LbTitulo);
        LbTitulo.setBounds(40, 10, 520, 60);

        lbNombre.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(102, 153, 255));
        lbNombre.setText("NOMBRE:");
        getContentPane().add(lbNombre);
        lbNombre.setBounds(70, 130, 130, 70);

        lbCedula.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        lbCedula.setForeground(new java.awt.Color(102, 153, 255));
        lbCedula.setText("CEDULA:");
        getContentPane().add(lbCedula);
        lbCedula.setBounds(70, 200, 110, 30);

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("EDAD:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 240, 90, 40);

        spEdad.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        getContentPane().add(spEdad);
        spEdad.setBounds(210, 250, 90, 32);

        tfNombre.setBackground(new java.awt.Color(255, 255, 255));
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });
        getContentPane().add(tfNombre);
        tfNombre.setBounds(210, 160, 221, 28);

        tfCedula.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tfCedula);
        tfCedula.setBounds(210, 200, 130, 28);

        LbPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/arbolmadre.jpg"))); // NOI18N
        getContentPane().add(LbPanel1);
        LbPanel1.setBounds(0, 0, 610, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void btRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistrarMouseClicked
        // TODO add your handling code here:
       
        Persona persona = new Persona (tfNombre.getText(),tfCedula.getText(),(int)spEdad.getValue());
        
        listarusu.addPersona(persona);
        setDefaults();

       //Persona persona new = Persona (tfNombre.getText(),tfCedula.getText(),(int)spEdad.getValue());
       // Persona persona new = Persona 
        //tfNombre.getText();tfCedula.getText();(int) spEdad.getValue()
        
    }//GEN-LAST:event_btRegistrarMouseClicked

    private void btListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btListaMouseClicked
        // TODO add your handling code here:
        
     new listarusu().setVisible(true);   
        
    }//GEN-LAST:event_btListaMouseClicked

     private void setDefaults() {
        tfNombre.setText("");
        tfCedula.setText("");
        spEdad.setValue(1);
       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbPanel1;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JButton btLista;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JSpinner spEdad;
    private javax.swing.JTextField tfCedula;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
